// Rust -> C++: autocxx only maps C++ to Rust, so exporting Rust functions
// still needs a (small) cxx bridge, reusing the type generated by autocxx.
// Its C++ side (sim_rs_bridge/bridge.h) is generated by CMake.
#[cxx::bridge(namespace = "rs")]
mod ffi {
    // Shared struct: same layout on both sides, fields visible from C++.
    struct Stats {
        mean: f64,
        stddev: f64,
        min: f64,
        max: f64,
    }

    unsafe extern "C++" {
        include!("field.hpp");
        #[namespace = "sim"]
        type Field = crate::cpp::sim::Field;
    }

    // Result<T> becomes a C++ exception (rust::Error)
    extern "Rust" {
        fn smooth(field: UniquePtr<Field>, passes: usize) -> Result<UniquePtr<Field>>;
        fn gradient(field: &Field, dx: f64) -> Result<UniquePtr<Field>>;
        fn stats(field: &Field) -> Result<Stats>;
    }
}

pub use ffi::Stats;
use crate::{gradient, smooth, stats};
