[package]
name = "rs"
version = "0.1.0"
authors = ["Pascal HAVÉ <hpwxf@haveneer.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
strum = { version = "0.20", features = ["derive"] }
auto_ops = "0.3.0"
procedural_macro = { path = "procedural_macro" }
futures = "0.3"
rand = "0.8.3"
# crates for julia example
image = "0.23.14"
num-complex = "0.4.0"
palette = "0.5.0"
compiler-test = { path = "./compiler-test" }

[dev-dependencies]
rstest = "0.11.0"
mockall = "0.10.2"

[workspace]
members = ["hello", "procedural_macro", "full-tree", "full-tree/libs/mylib1"]
