//! Same `c/clib.h` API as `manual.rs`, but the bindings themselves are
//! generated by `bindgen` at build time (see `build.rs`) instead of typed
//! by hand. This is the mainstream approach for real-world C libraries;
//! it costs a `libclang` build dependency, which is why it's opt-in behind
//! the `bindgen-compare` feature rather than the crate default.
//!
//! One genuine divergence worth noting: bindgen represents the C function
//! pointer parameter in `for_each` as `Option<extern "C" fn(...)>` (its
//! null-safety convention for function pointers), while `manual.rs` types
//! it as a plain, non-optional `extern "C" fn(...)`. Both bind the same C
//! symbol, so rustc's `clashing_extern_declarations` lint fires when both
//! modules are compiled together — silenced below since the mismatch is
//! intentional here (comparing two binding styles), not a bug.
#![allow(
    non_camel_case_types,
    non_snake_case,
    dead_code,
    clashing_extern_declarations
)]

include!(concat!(env!("OUT_DIR"), "/bindgen.rs"));

/// Calls case 1 through the generated bindings, so `main.rs` can check the
/// result against `safe::norm` (same C symbol, two different binding
/// sources — the numbers must match).
pub fn compare_point_norm(x: f64, y: f64) -> f64 {
    let p = Point { x, y };
    unsafe { point_norm(&p as *const Point) }
}
