#pragma once
#include <string>
#include <vector>

namespace sim {

// Plain C++ class, knowing nothing about Rust (no rust/cxx.h):
// its Rust binding is generated by autocxx (see src/lib.rs).
class Field {
public:
  explicit Field(size_t size);

  const std::string &name() const;
  void set_name(const std::string &name);
  size_t size() const;
  const std::vector<double> &values() const;
  std::vector<double> &values_mut();

private:
  std::string m_name;
  std::vector<double> m_values;
};

} // namespace sim
