// C++ application using a Rust library on its own C++ objects;
// the whole build is driven by CMake.
#include "field.hpp"
#include "rust/cxx.h"              // rust::Error
#include "sim_rs_bridge/bridge.h" // generated by cxxbridge from src/bridge.rs
#include <cmath>
#include <iostream>
#include <memory>

static void print(const sim::Field &f) {
  std::cout << f.name() << " =";
  for (double v : f.values()) {
    std::cout << ' ' << std::round(v * 100) / 100;
  }
  rs::Stats s = rs::stats(f); // shared struct, returned by value
  std::cout << "  (mean=" << s.mean << ", stddev=" << s.stddev << ")\n";
}

int main() {
  // Noisy step signal, built in C++
  const size_t n = 12;
  auto field = std::make_unique<sim::Field>(n);
  field->set_name("u");
  for (size_t i = 0; i < n; ++i) {
    field->values_mut()[i] = (i < n / 2 ? 0.0 : 1.0) + ((i % 2) ? 0.1 : -0.1);
  }
  const sim::Field *address = field.get();
  print(*field);

  // Ownership C++ -> Rust -> C++: the same object comes back, modified in place
  field = rs::smooth(std::move(field), 2);
  print(*field);
  std::cout << "same object: " << std::boolalpha << (field.get() == address)
            << '\n';

  // Borrowed by Rust, which returns a brand new C++ object
  std::unique_ptr<sim::Field> grad = rs::gradient(*field, 1.0);
  print(*grad);

  // Rust errors -> C++ exceptions
  try {
    rs::smooth(nullptr, 1);
  } catch (const rust::Error &e) {
    std::cout << "caught rust::Error: " << e.what() << '\n';
  }
}
