# To debug a workflow see: https://docs.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#enabling-debug-logging

name: Rust CI

on:
  push:
  schedule:
    - cron: '0 2 * * SAT'

jobs:
  build-rs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-20.04
          - name: macOS
            os: macOS-11
          - name: Windows
            os: windows-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Configure Python venv path
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            BIN_VENV=./venv/Scripts
          else
            BIN_VENV=./venv/bin
          fi
          echo "BIN_VENV=${BIN_VENV}" >> $GITHUB_ENV
      - name: build
        run: cd rs && cargo build
      - name: test
        run: cd rs && cargo test
      - name: demos
        run: |
          cd rs
          cargo run --bin quick-hash --manifest-path demos/quick-hash/Cargo.toml
          cargo run --bin cxx-interface --manifest-path demos/cxx-interface/Cargo.toml
      - name: examples
        run: |
          cd rs
          cargo run --example julia
          cargo run --example quick_julia
      - name: Python binding Unix
        shell: bash
        run: |
          cd rs/demos/pyrs-feature
          python3 -m venv venv
          . ${BIN_VENV}/activate
          pip3 install -r requirements.txt
          maturin develop
          ${BIN_VENV}/pytest

        # Disable since it is too expensive  
        # - name: benchmarks
        #  run: cd rs && cargo bench
        